'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Heart,Package,Scissors,X} from 'lucide-react';

const information = {
  about: {title:'A little about VELTO', sections:[['For a Warmer Home','VELTO brings colour and comfort to everyday spaces, with cushion covers, aprons, table covers and home textiles.'],['Explore the collection','Discover playful prints, warm textures and practical pieces for cooking, hosting and relaxing. Check each product for material, dimensions and care details.']]},
  help: {title:'Shopping FAQs',sections:[['What does VELTO offer?','Browse cushion covers, aprons, table covers, kitchen essentials and home decor. Use category tabs, search and filters to find a piece.'],['Do cushion covers include a filler?','Check the product dimensions and description. Items marked cover only do not include a cushion filler.'],['How do I check size and material?','Open a product to see dimensions, material, care information and product photos.'],['Can I place a real order?','Yes. Orders are confirmed only after Cashfree verifies the payment. If online payment is not configured, checkout is blocked instead of saving an unpaid order.']]},
  care: {title:'Product & fabric care',sections:[['Start with product details','Read each product care instruction and follow the label supplied with your item. Different fabrics, finishes and prints may need different treatment.'],['Cushion covers, aprons and table covers','For cotton textiles, use a gentle cold wash, air dry and avoid bleach unless the product label says otherwise.'],['Kitchen and decor pieces','Hand wash fragile decor items gently and dry with a soft cloth. Do not assume dishwasher, microwave or oven safety unless product information confirms it.']]},
  delivery: {title:'Shipping & delivery',sections:[['Order processing','Paid orders appear in the admin panel for packing and fulfilment. Customers can track the order status from their account.'],['Delivery support','Delivery timelines, courier details and shipping charges should be confirmed by VELTO for each active selling region.']]},
  returns: {title:'Returns & cancellations',sections:[['Cancellations','Cancellation requests must be handled by VELTO before the order is packed or shipped.'],['Returns and refunds','Return eligibility, refund timelines and final approval depend on product condition and VELTO policy. Payment refunds are processed through Cashfree or the original payment channel.']]},
  privacy: {title:'Privacy & data information',sections:[['Saved shopping activity','Your bag, wishlist, saved addresses and order history are stored with your signed-in account identifier.'],['Checkout information','Name, phone number, delivery address, pincode, order details and payment reference are saved for fulfilment and admin review. Card or UPI secrets are handled by Cashfree, not by this website.'],['Admin sign-in','Admin sign-in uses a secure session cookie that expires after eight hours. Signing out clears that cookie.']]},
  terms: {title:'Shopping information',sections:[['Product information','Catalogue, prices, stock, images and product details are managed from the admin panel. Review product information before placing an order.'],['Payment confirmation','Submitting checkout opens Cashfree. An order is created only after payment verification succeeds.'],['Order fulfilment','Admin users are responsible for packing, shipping, cancellation and customer communication after a paid order is received.']]},
  contact: {title:'Contact VELTO',sections:[['VELTO - TANUJA','PLOT NO F-24, F/F (OLD H NO. 30-B), KH NO. 40/12, POLE NO. MDKC 463, Rajdhani Park Road, New Delhi, West Delhi, Delhi - 110041.'],['Customer care','Email: info@velto.com. Mobile: +91 98102 88203.'],['Need product or order help?','Open a product to view details, or contact VELTO with your order reference for payment, delivery or return support.']]}
};

type Topic=keyof typeof information;

export default function StoreFooter({onShop,mode='live'}:{onShop:(category:string)=>void;mode?:string}){
 const [topic,setTopic]=useState<Topic|null>(null);
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(topic)dialog.current?.showModal();else dialog.current?.close()},[topic]);
 const link=(key:Topic,label:string)=><button onClick={()=>setTopic(key)}>{label}</button>;
 return <><footer className="velto-footer" aria-label="VELTO information">
  <section className="footer-values" aria-label="Our collection"><span><Heart size={22}/>Comfort for your corners</span><span><Scissors size={22}/>Prints with personality</span><span><Package size={22}/>Everyday home essentials</span></section>
  <section className="footer-columns">
   <div className="footer-story"><a href="/" className="footer-logo" aria-label="VELTO home"><img src="/velto-logo.png" alt="VELTO - For a Warmer Home" loading="lazy" decoding="async"/></a><h2>For a Warmer Home.</h2><p>Colourful cushion covers, aprons and thoughtful textiles for the spaces you love.</p>{link('about','Meet VELTO')}</div>
   <nav aria-label="Footer shop"><h3>Shop VELTO</h3>{['Cushion covers','Aprons','Table covers'].map(c=><button key={c} onClick={()=>onShop(c)}>{c}</button>)}<button onClick={()=>onShop('All pieces')}>View all products</button></nav>
   <nav aria-label="Customer care"><h3>Here to help</h3>{link('help','Shopping FAQs')}{link('care','Product & fabric care')}{link('delivery','Shipping & delivery')}{link('returns','Returns & cancellations')}{link('contact','Contact us')}</nav>
   <div className="footer-note"><span className="footer-note-label">GET IN TOUCH</span><h3>VELTO <span className="footer-contact-name">TANUJA</span></h3><address>Plot No. F-24, F/F (Old H No. 30-B),<br/>KH No. 40/12, Pole No. MDKC 463,<br/>Rajdhani Park Road, New Delhi,<br/>West Delhi, Delhi - 110041</address><div className="footer-contact-links"><a href="mailto:info@velto.com">info@velto.com</a><a href="tel:+919810288203">+91 98102 88203</a></div><button onClick={()=>setTopic('contact')}>Contact information <ArrowUpRight size={17}/></button><small>{mode==='test'?'Cashfree sandbox mode is active for internal verification.':'Secure payments via Cashfree.'}</small></div>
  </section>
  <section className="footer-bottom"><p>Copyright {new Date().getFullYear()} VELTO. All rights reserved.</p><nav aria-label="Store information">{link('privacy','Privacy & data')}{link('terms','Shopping information')}<a href="/admin">Admin panel <ArrowUpRight size={14}/></a></nav><span>For a Warmer Home.</span></section>
 </footer><dialog ref={dialog} className="footer-dialog" aria-labelledby="footer-dialog-title" onCancel={()=>setTopic(null)}><button className="close" aria-label="Close information" onClick={()=>setTopic(null)}><X/></button>{topic&&<div className="footer-dialog-content"><span className="eyebrow">VELTO / FOR A WARMER HOME</span><h2 id="footer-dialog-title">{information[topic].title}</h2>{information[topic].sections.map(([title,text])=><section key={title}><h3>{title}</h3><p>{text}</p></section>)}<button className="primary" onClick={()=>setTopic(null)}>Back to shopping</button></div>}</dialog></>;
}

